name: Java CI/CD

on:
  push:
    branches: [ "dev-be-main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build & Test
        run: mvn clean test

  send_email:
    needs: build-test
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Send CI/CD result email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI/CD Result: ${{ needs.build-test.result }}"
          to: nguyennmse184571@fpt.edu.vn
          from: GitHub CI/CD <minhnguyen08112004@gmail.com>
          body: |
            Result: ${{ needs.build-test.result }}
            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

